add_newline = true
continuation_prompt = "∙  ┆ "
format = "$nix_shell$os$cmd_duration$directory$container$git_branch $git_status$python$nodejs$lua$rust$java$c$golang$status$line_break$character${custom.space}"

[c]
format = "[$symbol ](blue)"
symbol = " "

[character]
error_symbol = "[ 󰅙](bold fg:red)"
success_symbol = "[ ](bold fg:purple)"

[cmd_duration]
format = "[ $duration](fg:yellow)"
min_time = 1000

[container]
format = "[$symbol ](yellow dimmed)"
symbol = " 󰏖"

[custom.space]
format = "  "
when = "! test $env"

[directory]
format = " [](fg:bright-black)[$path](bg:bright-black fg:white)[](fg:bright-black)"
truncation_length = 6
truncation_symbol = "~/󰇘/"

[git_branch]
format = "[[   on](fg:white) $symbol $branch](fg:purple)(:$remote_branch)"
style = ""
symbol = "󰘬"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_status]
ahead = " ahead"
behind = " behind"
conflicted = " conflicted"
deleted = " deleted"
diverged = " diverged"
format = "($conflicted)($ahead)($behind)($diverged)($untracked)($stashed)($modified)($renamed)($deleted)"
modified = " modified"
renamed = " renamed"
staged = "`++($count)(green)`"
stashed = " stashed"
untracked = " untracked"

[golang]
format = "[$symbol ](blue)"
symbol = " "

[java]
format = "[$symbol ](red)"
symbol = " "

[line_break]
disabled = false

[lua]
format = "[$symbol ](blue)"
symbol = " 󰢱"

[nix_shell]
disabled = false
format = "[](fg:white)[ ](bg:white fg:black)[](fg:white) "

[nodejs]
format = "[$symbol ](yellow)"
symbol = "  "

[os]
disabled = false
format = "$symbol"

[os.symbols]
Arch = "[ ](fg:bright-blue)"
Debian = "[ ](fg:red))"
EndeavourOS = "[ ](fg:purple)"
Fedora = "[ ](fg:blue)"
NixOS = "[ ](fg:blue)"
SUSE = "[ ](fg:green)"
Ubuntu = "[ ](fg:bright-purple)"
openSUSE = "[ ](fg:green)"

[python]
format = "[$symbol ](yellow)"
symbol = " "

[rust]
format = "[$symbol ](red)"
symbol = " "

[status]
disabled = false
format = "[$symbol](fg:red)"
map_symbol = true
not_executable_symbol = "permissions"
not_found_symbol = "not found"
sigint_symbol = "󰂭 "
signal_symbol = "󱑽 "
success_symbol = ""
symbol = ""

